name: Generate Release on Master Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions: # <-- Añade esta sección
  contents: write # Permiso para escribir en el repositorio (necesario para tags y releases)
  pull-requests: write # Permiso para leer información de Pull Requests (necesario para el título y cuerpo del PR)

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR title and body
        id: pr_info
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body || 'No description provided.' }}"
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_OUTPUT
          echo "PR_BODY=$PR_BODY" >> $GITHUB_OUTPUT

      - name: Generate version number
        id: generate_version
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')
          echo "Generated version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a v${{ steps.generate_version.outputs.VERSION }} -m "Release v${{ steps.generate_version.outputs.VERSION }}"
          git push origin v${{ steps.generate_version.outputs.VERSION }} # Aquí es donde fallaba sin permisos

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.generate_version.outputs.VERSION }}
          release_name: ${{ steps.pr_info.outputs.PR_TITLE }}
          body: ${{ steps.pr_info.outputs.PR_BODY }}
          draft: false
          prerelease: false
